<?php
    include_once("getip.php");
    include_once("getbrowser.php");
    include_once("methods.php");
    require_once("connect.php");
    include_once("sessioncheck.php");
    include_once("sitesettings.php");
    include_once("settings.php");
?>